coreos/fedora-coreos-streams

README.md, streams/testing.json
Creating from https://github.com/coreos/fedora-coreos-tracker using `fedora-coreos-stream-generator -releases=https://builds.coreos.fedoraproject.org/prod/streams/testing/releases.json  -output-file=testing.json --pretty-print`
=> Stream metadata for testing release 30.20190715.0

COPYING, LICENSE
Copy the permissive license from fedora-coreos-config.
Closes #4.
=> Add repository license

updates/testing.json
This sets up a rollout for `30.20190801.0`, linearly increasing over
a 2 hours window (`120 minutes`), starting at epoch `1565017200`.
```
$ date -u -d @1565017200
Mon Aug  5 15:00:00 UTC 2019
```
=> testing: setup linear rollout for 30.20190801.0

ISSUE_TEMPLATE/testing.md, README.md, release-prereqs.md
This is a (hopefully) complete guide to doing an FCOS release as of
today. Lots of warts and rough bits. Though I'm interested in kind of
using it too as a living document to track the next steps in
streamlining the process (hence the couple of "in the future" items in
there).
=> Add release checklist

updates/testing.json
This reworks the updates-metadata format, following the discussion at https://github.com/coreos/fedora-coreos-streams/pull/10.
This PR only alters the schema, but it should not affect rollouts and other content.
=> updates/testing: change metadata schema

ISSUE_TEMPLATE/testing.md
This fixes markdown syntax, by removing unnecessary escapes in
backtick-ed content.
=> checklist/updates: fix markdown syntax

ISSUE_TEMPLATE/testing.md, updates/testing.json
Ancient machines with high rollout wariness should be able to update to the most recent fully-rolled-out version, even after a new rollout has started.  Otherwise, launches of e.g. old AMIs will sometimes not receive security updates in a timely fashion.
@lucab This appears to be the correct syntax from reading https://github.com/lucab/exp-dumnati/blob/master/src/policy.rs.  Could you confirm?
=> updates/testing: add last-known-good version

updates/testing.json
Closes: https://github.com/coreos/fedora-coreos-streams/issues/30
=> updates/testing: mark 30.20191014.1 as a barrier

updates/testing.json
We fully rolled out `31.20191127.1` on `testing`, but it looks like
auto-updating from some old releases might not be safe.
Temporarily hiding this rollout while we investigate
https://github.com/coreos/fedora-coreos-tracker/issues/322.
=> testing: temporarily hide 31.20191127.1 rollout

streams/testing.json, updates/testing.json
Rollout for `31.20191211.1` on `testing`, starting at `Thu Dec 12 14:30:00 UTC 2019` and rolling for 48h.
=> testing: rollout 31.20191211.1

ISSUE_TEMPLATE/stable.md, README.md
Prep for actually being able to do a release.
https://github.com/coreos/fedora-coreos-tracker/issues/331
=> Add instructions for stable release

streams/testing.json, updates/testing.json
Rollout for `31.20191217.2.0` on `testing`, starting at `Thu Dec 19 14:30:00 UTC 2019` and rolling for 24h.
=> testing: rollout 31.20191217.2.0

streams/stable.json, updates/stable.json
This is the first release so there's no need to have a long rollout.
Though for fun I did `"duration_minutes": 5` as a test for Cincinnati.
=> stable: rollout 31.20200108.3.0

.cci.jenkinsfile, Makefile
Do some basic syntax validation, as well as printing rollout details to
make it easier for reviewers. E.g.:
```
$ make print-rollouts
testing rollout of 31.20200127.2.0 scheduled for 2020-02-03 09:00:00 UTC for 1440m (24.0h)
stable rollout of 31.20200118.3.0 scheduled for 2020-02-03 09:00:00 UTC for 4320m (72.0h)
```
=> ci: hook up to CoreOS CI

ISSUE_TEMPLATE/stable.md, ISSUE_TEMPLATE/testing.md
This updates the default FCOS Cincinnati endpoint, switching from
staging infrastructure to production one.
Ref: https://github.com/coreos/fedora-coreos-tracker/issues/347
=> template: update FCOS Cincinnati endpoint (prod)

streams/stable.json, streams/testing.json, updates/stable.json, updates/testing.json
This contains two rollouts:
* stable, 31.20200323.3.2
* testing, 31.20200407.2.2
=> rollouts: stable and testing, 2020-04-08

ISSUE_TEMPLATE/stable.md, ISSUE_TEMPLATE/testing.md
This means we don't need to open a releng ticket and wait for it to
get processed.
=> templates: ostree imports are happening during release job now

Makefile, print-rollout.py, streams/next.json, updates/next.json
This is the first release, so there's nothing actually to update *from*
within this stream. Hence why the update rollout is already at 1.0.
=> next: rollout 32.20200416.1.0

ISSUE_TEMPLATE/next.md, ISSUE_TEMPLATE/stable.md, ISSUE_TEMPLATE/testing.md
Each time we finish up a release let's create the tickets for the next
one. This will allow for us to plan appropriately for them and also make
sure any scheduling conflicts are addressed early.
=> issue template: add notes about creating tickets for next release

updates/testing.json
As a mild mitigation for
https://github.com/coreos/fedora-coreos-tracker/issues/481, let's remove
the previous rollout from the graph so that no more nodes get into that
state.
=> updates/testing: remove previous rollout

print-rollout.py, updates/next.json, updates/stable.json, updates/testing.json
This drops all completed rollouts, mitigating rpm-ostree bug
while preparing for the next triple round of releases.
Ref: https://github.com/coreos/fedora-coreos-tracker/issues/481
=> updates: stop all rollouts

ISSUE_TEMPLATE/next.md, ISSUE_TEMPLATE/stable.md, ISSUE_TEMPLATE/testing.md, release-prereqs.md
We have a job that does that now:
coreos/fedora-coreos-pipeline#236
This allows us to drop the requirement on releasers having direct access
to the S3 bucket.
=> templates: don't manually sync to S3 anymore 

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
This schedules rollouts for latest stable/testing/next release,
starting on 2020-06-03. The rollout for testing is extra long
since this is an update that involved a major Fedora version
rebase.
=> updates: triple rollout on 2020-06-03

streams/next.json
We accidentally ran the release job against the wrong release for
next so let's roll this back briefly while we fix things up.
https://github.com/coreos/fedora-coreos-streams/issues/109#issuecomment-638361523
=> streams/next: rollback stream metadata to 32.20200517.1.0 briefly

updates/next.json, updates/testing.json
This drops all completed rollouts, mitigating rpm-ostree bug
while preparing for an intermediate release of testing/next.
=> updates: stop all rollouts for next/testing

streams/next.json, streams/testing.json, updates/next.json, updates/testing.json
Since `next` is a little more risky of a stream we can go ahead and
roll it out on Friday. For `testing` we'll wait til Monday. Since
the content in both releases is identical rolling out `next` early
will give us an early indication of if there is a problem.
=> updates: rollout next on 06/12 and testing on 06/15

streams/next.json, updates/next.json
This release bumps the package set and also restores persistent NIC
naming. See the following issue for context:
https://github.com/coreos/fedora-coreos-tracker/issues/484
=> next: rollout 32.20200625.1.0

streams/stable.json, updates/stable.json
This a barrier release for https://github.com/coreos/fedora-coreos-tracker/issues/484
This also adds the GCP Cloud launchable stream.
=> stable: rollout 32.20200615.3.0 (barrier release)

streams/next.json, streams/testing.json
`coreos-installer download` won't download the PXE rootfs artifact, since it's smaller than 1 MiB.
=> {next,testing}: revert metal artifacts

updates/next.json, updates/testing.json
We found an issue with the PXE rootfs artifact where coreos-installer
can't verify it [1]. We're going to do a new set of builds so let's stop
the next/testing rollouts of 32.20200809.1.0 and 32.20200809.2.0 so we
don't update users two times in as many days.
[1] https://github.com/coreos/fedora-coreos-streams/issues/158#issuecomment-672013148
=> updates: stop next/testing rollouts

streams/next.json, streams/testing.json, updates/next.json, updates/testing.json
* testing rollout of 32.20200907.2.0 scheduled for 2020/09/09 10:00 UTC for 2880m (48.0h)
* next rollout of 32.20200907.1.0 scheduled for 2020/09/09 10:00 UTC for 2880m (48.0h)
=> updates: dual rollout (testing/next) on 2020-09-09

updates/stable.json
This fixes a mistake in the rollout start year (2019 vs 2020).
=> stable: fix 32.20200907.3.0 rollout start year

print-rollout.py
That way it's more obvious if e.g. we mess up the month or year.
=> ci/print-rollout: print time delta between now and rollout start

ISSUE_TEMPLATE/next.md, ISSUE_TEMPLATE/stable.md, ISSUE_TEMPLATE/testing.md
This blurries the start date example, in order to prevent blind
copy-pasting mistakes.
It tries to avoid future human mistakes like https://github.com/coreos/fedora-coreos-streams/issues/183#issuecomment-697344574.
=> templates: blurry start date

updates/stable.json, updates/testing.json
As part of the procedure to move to the next major Fedora release
we are adding a barrier for the last release of Fedora CoreOS based
on Fedora 31 content. This is a guarantee that systems have the
appropriate keys to validate the commits signed by the latest builds.
Note: there were no F31 releases on the `next` stream so skip adding
the barrier release there.
See:
- https://github.com/coreos/fedora-coreos-tracker/issues/480#issuecomment-631724629
- https://github.com/coreos/fedora-coreos-config#moving-to-a-new-major-version-n-of-fedora
=> updates: add barrier releases as part of f33 bump SOP

streams/stable.json, streams/testing.json, updates/stable.json, updates/testing.json
Double rollouts:
* 32.20201004.2.0 on `testing`
* 32.20200923.3.0 on `stable`
=> Rollout testing and stable on 2020-10-07

print-rollout.py
That should make it even easier to tell when the rollout is for
reviewers.
Having the delta is nice, but it becomes stale if the CI run happened
hours ago.
=> print-rollout.py: print time in familiar timezones

ISSUE_TEMPLATE/next.md, ISSUE_TEMPLATE/stable.md, ISSUE_TEMPLATE/testing.md
This was changed in
https://github.com/coreos/fedora-coreos-pipeline/pull/270.
=> templates: update links to new AWS/GCP kola jobs

streams/testing.json, updates/testing.json
```
testing
version: 33.20201116.2.0
start: 2020-11-18 14:00:00+00:00 UTC (in 2:40:30)
2020-11-18 09:00:00-05:00 Raleigh/New York/Toronto
2020-11-18 15:00:00+01:00 Berlin/France/Poland
```
=> testing: rollout 33.20201116.2.0

updates/testing.json
This is the first f33 release on the `testing` stream. Let's make
it a barrier as agreed upon in https://github.com/coreos/fedora-coreos-tracker/issues/646.
=> testing: add barrier to the 33.20201116.2.0 release.

streams/next.json, updates/next.json
```
next
version: 33.20201117.1.0
start: 2020-11-19 16:00:00+00:00 UTC (in 1:44:46)
2020-11-19 11:00:00-05:00 Raleigh/New York/Toronto
2020-11-19 17:00:00+01:00 Berlin/France/Poland
```
=> next: rollout 33.20201117.1.0

updates/testing.json
This reverts commit 9fa9a0655b542de942fd154419c41ab0f7c010b6.
The issue is a problem, but a known issue and not one introduced
by this update.
=> Revert "testing: pause rollout of 33.20201201.2.1"

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
Async release for sudo CVE-2021-3156:
https://bodhi.fedoraproject.org/updates/FEDORA-2021-2cb63d912a
- stable: 33.20210104.3.1
- testing: 33.20210117.2.1
- next: 33.20210117.1.1
=> Triple rollout for sudo CVE-2021-3156

streams/stable.json, updates/stable.json
This reverts commit 48260bc75e8edc41a00d6fff2dc498ee31210523.
This stable release is downgrading sudo back to the previous version
with CVE-2021-3156:
https://github.com/coreos/fedora-coreos-config/pull/834/commits/cb53902e1fe2a5f75dab3c3d946d763267ee8d18#r569584509
=> Revert "stable: rollout 33.20210117.3.1"

streams/stable.json, updates/stable.json
This includes fixes for both CVE-2021-3156 and CVE-2021-3347.
=> stable: rollout 33.20210117.3.2

.github/workflows/promote-config.yml, ISSUE_TEMPLATE/next.md, ISSUE_TEMPLATE/stable.md, ISSUE_TEMPLATE/testing.md
This is the first step in simplifying the release process. Allow users
to simply add the `ok-to-promote` label on the issue which in turn
triggers an action to run the promotion script and open a PR.
=> Use GitHub Actions to promote configs

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
Rollouts scheduled on `2021/04/14 14:30UTC`:
* stable:  `33.20210328.3.0`
* testing: `33.20210412.2.0`
* next: `34.20210413.1.0`
=> Triple update on 2021-04-14

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
https://github.com/coreos/fedora-coreos-streams/issues/301
https://github.com/coreos/fedora-coreos-streams/issues/302
https://github.com/coreos/fedora-coreos-streams/issues/303
```
stable
version: 33.20210426.3.0
start: 2021-05-05 14:00:00+00:00 UTC (in 0:48:19)
2021-05-05 10:00:00-04:00 Raleigh/New York/Toronto
2021-05-05 16:00:00+02:00 Berlin/France/Poland
next
version: 34.20210503.1.0
start: 2021-05-05 14:00:00+00:00 UTC (in 0:48:19)
2021-05-05 10:00:00-04:00 Raleigh/New York/Toronto
2021-05-05 16:00:00+02:00 Berlin/France/Poland
testing
version: 34.20210427.2.0
start: 2021-05-05 14:00:00+00:00 UTC (in 0:48:19)
2021-05-05 10:00:00-04:00 Raleigh/New York/Toronto
2021-05-05 16:00:00+02:00 Berlin/France/Poland
```
=> Triple rollout

updates/testing.json
We're going to respin it for runc's CVE-2021-30465 (symlink exchange
attack). Might as well try to minimize the number of nodes that will
reboot again.
See: https://github.com/coreos/fedora-coreos-streams/issues/317
=> testing: stop rollout of 34.20210518.2.0

streams/testing.json, updates/testing.json
Contains runc-2:1.0.0-378.rc95.fc34 which has fix for CVE-2021-30465
(symlink exchange attack).
=> testing: rollout 34.20210518.2.1

.github/workflows/promote-config.yml
We're disabling `next-devel` for now while it's in lockstep with
`testing-devel`.
xref: https://github.com/coreos/fedora-coreos-pipeline/pull/343
=> promote-config.yml: use testing-devel for next promotion

updates/next.json, updates/stable.json, updates/testing.json
This update barrier is pretty much useless because of
https://github.com/coreos/fedora-coreos-tracker/issues/749, but we
decided to put them in place anyway just to keep following the process.
As far as the process goes. See past discussion on this topic:
- https://github.com/coreos/fedora-coreos-tracker/issues/480#issuecomment-631724629
- https://docs.fedoraproject.org/en-US/fedora-coreos/update-barrier-signing-keys/
=> updates: add update barriers for N-2 (F32) for key rotation

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
* stable: 34.20210529.3.0
* testing: 34.20210611.2.0
- adds barrier due to https://github.com/coreos/fedora-coreos-tracker/issues/829
* next: 34.20210611.1.0
- adds barrier due to https://github.com/coreos/fedora-coreos-tracker/issues/829
=> Triple rollout on 2021-06-15

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
Rollouts scheduled on `2021/06/29 14:30UTC`:
* stable:  `34.20210611.3.0`
* testing: `34.20210626.2.0`
* next: `34.20210626.1.0`
=> Triple update on 2021-06-29

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
- stable (34.20210626.3.1)
- testing(34.20210711.2.0)
- next (34.20210711.1.1)
=> Triple rollout on 2021-07-14

streams/next.json, streams/testing.json, updates/next.json, updates/testing.json
```
next
version: 34.20210711.1.2
start: 2021-07-21 18:00:00+00:00 UTC (in 0:26:40)
2021-07-21 14:00:00-04:00 Raleigh/New York/Toronto
2021-07-21 20:00:00+02:00 Berlin/France/Poland
duration: 1440m (24.0h)
testing
version: 34.20210711.2.1
start: 2021-07-21 18:00:00+00:00 UTC (in 0:26:36)
2021-07-21 14:00:00-04:00 Raleigh/New York/Toronto
2021-07-21 20:00:00+02:00 Berlin/France/Poland
duration: 1440m (24.0h)
```
=> Roll out next 34.20210711.1.2 and testing 34.20210711.2.1

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
```
next
version: 34.20210725.1.0
start: 2021-07-28 16:00:00+00:00 UTC (in 4:47:51)
2021-07-28 12:00:00-04:00 Raleigh/New York/Toronto
2021-07-28 18:00:00+02:00 Berlin/France/Poland
testing
version: 34.20210725.2.0
start: 2021-07-28 16:00:00+00:00 UTC (in 4:47:51)
2021-07-28 12:00:00-04:00 Raleigh/New York/Toronto
2021-07-28 18:00:00+02:00 Berlin/France/Poland
stable
version: 34.20210711.3.0
start: 2021-07-28 16:00:00+00:00 UTC (in 4:47:51)
2021-07-28 12:00:00-04:00 Raleigh/New York/Toronto
2021-07-28 18:00:00+02:00 Berlin/France/Poland
```
=> Triple rollout on 2021-07-28

.github/workflows/promote-config.yml
I'm not sure whether issue permission is needed, but be conservative to avoid breakage.
=> workflows: limit permissions to reading repo contents and issues

streams/next.json, updates/next.json
This is the first stream release with aarch64 artifacts!
```
next
version: 34.20210904.1.0 (latest)
start: 2021-09-07 15:00:00+00:00 UTC (in 10:27:00)
2021-09-07 11:00:00-04:00 Raleigh/New York/Toronto
2021-09-07 17:00:00+02:00 Berlin/France/Poland
```
=> next: rollout 34.20210904.1.0

streams/stable.json, streams/testing.json, updates/stable.json, updates/testing.json
stable: rollout 34.20210821.3.0
testing: rollout 34.20210904.2.0
This release also includes aarch64 artifacts.
=> Rollout for testing and stable streams

streams/next.json, streams/stable.json, streams/testing.json
During the previous rollout, stream-metadata-go had not been bumped. This
resulted in some important changes to be missing from generated metadata 
in the previous rollout (such as parsing of azure stack artifact metadata).
Lets regenerate the data using the latest version of stream-metadata-go.
related: https://github.com/coreos/fedora-coreos-tracker/issues/960
=> stable, testing, next: regenerate stream metadata to include azure stack

ISSUE_TEMPLATE/next.md, ISSUE_TEMPLATE/stable.md, ISSUE_TEMPLATE/testing.md
This is part of the release job now:
https://github.com/coreos/fedora-coreos-pipeline/pull/365
=> templates: stop manual pull test from previous QEMU image

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
```
stable
version: 34.20210904.3.0 (latest)
start: 2021-09-21 15:00:00+00:00 UTC (in 0:38:12)
2021-09-21 11:00:00-04:00 Raleigh/New York/Toronto
2021-09-21 17:00:00+02:00 Berlin/France/Poland
next
version: 34.20210919.1.0 (latest)
start: 2021-09-21 15:00:00+00:00 UTC (in 0:38:12)
2021-09-21 11:00:00-04:00 Raleigh/New York/Toronto
2021-09-21 17:00:00+02:00 Berlin/France/Poland
testing
version: 34.20210919.2.0 (latest)
start: 2021-09-21 15:00:00+00:00 UTC (in 0:38:12)
2021-09-21 11:00:00-04:00 Raleigh/New York/Toronto
2021-09-21 17:00:00+02:00 Berlin/France/Poland
```
=> Triple rollout on 2021-09-20

release-prereqs.md
Over time we have automated some things so that we don't require as
many local git repos etc.. Let's update to the current requirements and
also update the current requirements to be a little more verbose/obvious.
=> release-prereqs.md: drop requirements no longer needed

.github/workflows/promote-config.yml
Fedora 35 Beta is now GO. Start shipping from `next-devel`.
=> promote-config: promote next-devel to next

ISSUE_TEMPLATE/next.md, ISSUE_TEMPLATE/stable.md, ISSUE_TEMPLATE/testing.md
It's mentioned in the prereqs that it should be updated, but that's not
as strong as actually having it be a task.
=> templates: add task for updating fedora-coreos-stream-generator

ISSUE_TEMPLATE/next.md, ISSUE_TEMPLATE/stable.md, ISSUE_TEMPLATE/testing.md
When we have separate checkboxes for subtasks, don't require the operator to also roll up those checkboxes into a top-level one.
=> templates: drop redundant checkboxes

RELEASE.md
With a large number of release executors, it's difficult for any one of them to build up a lot of experience with the release process.  There's also no well-defined plan for assigning an executor to ad-hoc releases; we've been doing it ad hoc.  Address both issues by creating a "standby release executor" role to handle ad-hoc releases, and moving some of the more experienced executors over to it.  The folks on the new list have volunteered for the role; cc @lucab @cverna who are also eligible.
Also drop @sinnykumari from the executor list.  Sinny has less time to be involved in Fedora CoreOS these days, and is stepping back from handling releases for now.  Thanks Sinny for all your work running releases for the last couple years!
=> RELEASE: create new "standby executor" role

.github/workflows/rollout.yml
If we make a shallow clone of this repo, and the downstream fork doesn't contain all of its parent commits, GitHub rejects our push with `shallow update not allowed`.  To avoid making assumptions about the state of the fork, make a full clone of this repo.
=> workflows/rollout: fix pushing to coreosbot-releng fork

RELEASE.md
Per https://github.com/coreos/fedora-coreos-streams/pull/403#issuecomment-957173597.  Four seems like a good number of regular executors.
cc @lucab
=> RELEASE: move lucab to standby release executor

ISSUE_TEMPLATE/next.md, ISSUE_TEMPLATE/stable.md, ISSUE_TEMPLATE/testing.md
For convenience, we'd like all streams to be updated in the same PR.  (Also, there will be merge conflicts if a second PR is created before the first one merges.)  Add a sync step to make this explicit.
=> templates: several updates

ISSUE_TEMPLATE/next.md, ISSUE_TEMPLATE/stable.md, ISSUE_TEMPLATE/testing.md
The next step asks for a link to the aarch64 job, but the instructions didn't make it clear that the job is started automatically.
Requested in https://github.com/coreos/fedora-coreos-streams/pull/407#issuecomment-958055372.
=> templates: note that the x86_64 pipeline automatically starts multi-arch

streams/testing.json, updates/testing.json
```
testing
version: 35.20211029.2.0 (latest)
start: 2021-11-10 14:00:00+00:00 UTC (in 16:47:58)
2021-11-10 09:00:00-05:00 Raleigh/New York/Toronto
2021-11-10 15:00:00+01:00 Berlin/France/Poland
duration: 4320m (72.0h)
```
=> testing: rollout 35.20211029.2.0

.github/workflows/promote-config.yml
Use the metadata added in https://github.com/coreos/fedora-coreos-pipeline/pull/451 to decide which stream to promote to `next`.
Untested.
=> workflows: automatically choose promotion source for `next-devel`

ISSUE_TEMPLATE/next.md, ISSUE_TEMPLATE/stable.md, ISSUE_TEMPLATE/testing.md, RELEASE.md
Automatically fill in a template issue title, rather than requiring the release executor to copy it from the issue body.
=> RELEASE: create release checklists with template issue title

streams/next.json, streams/testing.json, updates/next.json, updates/testing.json
Mitigate AWS Xen boot failures from https://github.com/coreos/fedora-coreos-tracker/issues/1066 until we can roll out a fix.  We can continue allowing new launches of the affected versions on non-AWS platforms, but update edges aren't platform-specific so drop those for everyone.
Don't roll back `ap-southeast-3`, since there's no previous image to roll back to.  There's no point in breaking that region completely.
=> Roll back `testing` and `next` on AWS only; delete update edges

.github/workflows/rollout.yml
It saves a bunch of code.
For consistency and simplicity, we no longer autodetect the destination repo for the branch push.  It's now necessary to change or disable the push-to-fork parameter when testing changes to this workflow in a fork.
=> workflows/rollout: switch to `create-pull-request` action

ISSUE_TEMPLATE/next.md, ISSUE_TEMPLATE/stable.md, ISSUE_TEMPLATE/testing.md
We moved our pipeline from CentOS CI to Fedora's new OpenShift
cluster. Let's update our links to be accurate now.
=> templates: update links to pipeline jobs

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
Requested by @ravanelli via [GitHub workflow](https://github.com/coreos/fedora-coreos-streams/actions/workflows/rollout.yml) ([source](https://github.com/coreos/fedora-coreos-streams/blob/main/.github/workflows/rollout.yml)).
=> Roll out stable 35.20220116.3.0, testing 35.20220131.2.0, next 35.20220131.1.0

ISSUE_TEMPLATE/next.md, ISSUE_TEMPLATE/stable.md, ISSUE_TEMPLATE/testing.md
We moved from a openshift buildconfig based approach to a jenkins
job approach in https://github.com/coreos/fedora-coreos-pipeline/pull/468
=> templates: update with new jenkins job URLs

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
Requested by @saqibali-2k via [GitHub workflow](https://github.com/coreos/fedora-coreos-streams/actions/workflows/rollout.yml) ([source](https://github.com/coreos/fedora-coreos-streams/blob/main/.github/workflows/rollout.yml)).
=> Roll out stable 35.20220131.3.0, testing 35.20220213.2.0, next 35.20220213.1.0

.github/workflows/stream-diff.yml, ci/genericize-stream.py
Stream metadata updates are large diffs containing mostly routine changes, with a small chance of serious breakage.  Reviewing them is tedious and reviewers have overlooked problems in the past.  To aid PR reviews, add a CI job that "genericizes" stream metadata from both the base branch and the PR (by replacing strings that routinely change) and then compares the two.  If there are any remaining differences, fail the job (which will not block merge) and add annotation boxes to the GitHub diff view that mark the unexpected differences:
Proposed by @jlebon.
=> workflows: add job to check stream metadata for unexpected changes

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 35.20220213.3.0, testing 35.20220227.2.0, next 35.20220227.1.0

streams/next.json, streams/testing.json, updates/next.json, updates/testing.json
=> Roll out testing 35.20220227.2.1, next 35.20220227.1.1

.github/workflows/print-rollouts.yml
Old package versions can be removed from the mirror, which could cause job failures.
=> workflows: `apt-get update` before installing packages

ISSUE_TEMPLATE/next.md, ISSUE_TEMPLATE/stable.md, ISSUE_TEMPLATE/testing.md
Sometimes we need this and it would be nice to have it accessible
in the templates rather than having to find the steps when you do
need it.
=> templates: re-add manual steps for config promotion

streams/next.json, updates/next.json
next
version: 36.20220325.1.0 (latest)
start: 2022-03-29 14:00:00+00:00 UTC (in 13:32:54)
2022-03-29 10:00:00-04:00 Raleigh/New York/Toronto
2022-03-29 16:00:00+02:00 Berlin/France/Poland
Signed-off-by: Renata Andrade Matos Ravanelli <rravanel@redhat.com>
=> Roll out next 36.20220325.1.0

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
Requested by @saqibali-2k via [GitHub workflow](https://github.com/coreos/fedora-coreos-streams/actions/workflows/rollout.yml) ([source](https://github.com/coreos/fedora-coreos-streams/blob/main/.github/workflows/rollout.yml)).
=> Roll out stable 35.20220327.3.0, testing 35.20220410.2.1, next 36.20220410.1.1

.github/workflows/stream-diff.yml, ci/genericize-stream.py
The stream diff currently warns on fedora-coreos-stream-generator version changes, even routine ones, and the false positive can lead to confusion.  Assume that stream metadata is built with the latest tag of fedora-coreos-stream-generator.  For all streams that have been changed in the current PR, update the old genericized metadata to reference the new tag, avoiding the change warning.  For streams that haven't, we can skip the comparison entirely.
This will still warn if stream metadata is built from an old generator tag, or from a generator commit that has not been tagged.
=> workflows: don't warn on expected fedora-coreos-stream-generator bumps

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 35.20220410.3.1, testing 35.20220424.2.0, next 36.20220426.1.0

.github/workflows/rollout.yml
After regenerating stream metadata for an unchanged stream, we skip committing it, but leave the regenerated metadata in the work tree with an updated timestamp.  The create-pull-request action notices those changes and commits them with a generic commit title (`[create-pull-request] automated change`).
Discard any uncommitted changes to avoid the spurious automatic commit.
Fixes #446.
=> workflows/rollout: don't bump metadata timestamps of unchanged streams

release-notes/next.yml, release-notes/stable.yml, release-notes/testing.yml
Import a set of YAML documents that list issues fixed in a given Fedora
CoreOS release.
This list will be displayed as part of the release notes at
https://getfedora.org/en/coreos
See: https://github.com/coreos/fedora-coreos-tracker/issues/194
=> release-notes: Initial import for all streams

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
Requested by @saqibali-2k via [GitHub workflow](https://github.com/coreos/fedora-coreos-streams/actions/workflows/rollout.yml) ([source](https://github.com/coreos/fedora-coreos-streams/blob/main/.github/workflows/rollout.yml)).
=> Roll out stable 36.20220505.3.2, testing 36.20220522.2.1, next 36.20220522.1.0

release-notes/next.yml, release-notes/stable.yml, release-notes/testing.yml
Add notes for the following releases:
- next: 36.20220505.1.0 36.20220430.1.0 36.20220426.1.0 36.20220418.1.0 36.20220325.1.0
- testing: 36.20220505.2.0 35.20220424.2.0
- stable: 35.20220424.3.0 35.20220410.3.1
=> release-notes: Update for new releases

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 36.20220522.3.0, testing 36.20220605.2.0, next 36.20220605.1.0

.github/workflows/promote-config.yml
Let's say exactly what we expect instead of failing on `src_stream`
being undefined.
=> workflows/promote-config: print nicer error if issue title is malformed

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
Requested by @ravanelli via [GitHub workflow](https://github.com/coreos/fedora-coreos-streams/actions/workflows/rollout.yml) ([source](https://github.com/coreos/fedora-coreos-streams/blob/main/.github/workflows/rollout.yml)).
=> Roll out stable 36.20220605.3.0, testing 36.20220618.2.0, next 36.20220618.1.1

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 36.20220618.3.1, testing 36.20220703.2.1, next 36.20220703.1.1

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 36.20220716.3.1, testing 36.20220723.2.2, next 36.20220723.1.2

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 36.20220723.3.1, testing 36.20220806.2.0, next 36.20220806.1.2

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 36.20220806.3.0, testing 36.20220820.2.0, next 36.20220820.1.0

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 36.20220820.3.0, testing 36.20220906.2.0, next 36.20220906.1.0

updates/next.json
As discussed in the meeting today:
https://github.com/coreos/fedora-coreos-tracker/issues/480#issuecomment-1247314065
=> updates: add barrier for final last F36 `next` build

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 36.20220906.3.2, testing 36.20220918.2.2, next 37.20220918.1.1

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 36.20220918.3.0, testing 36.20221001.2.0, next 37.20221003.1.0

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 36.20221001.3.0, testing 36.20221014.2.0, next 37.20221015.1.0

release-notes/next.yml
Also add an entry for `37.20221008.1.0`, which we had missed in the past.
=> release-notes: updates for the 37.20221021.1.0 `next` release

streams/next.json, streams/testing.json, updates/next.json, updates/testing.json
=> Roll out testing 36.20221014.2.1, next 37.20221021.1.1

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
Requested by @lucab via [GitHub workflow](https://github.com/coreos/fedora-coreos-streams/actions/workflows/rollout.yml) ([source](https://github.com/coreos/fedora-coreos-streams/blob/main/.github/workflows/rollout.yml)).
=> Roll out stable 36.20221014.3.1, testing 36.20221030.2.1, next 37.20221031.1.0

streams/next.json, streams/testing.json, updates/next.json, updates/testing.json
=> Roll out testing 36.20221030.2.3, next 37.20221106.1.0

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 36.20221030.3.0, testing 37.20221106.2.1, next 37.20221111.1.0

ISSUE_TEMPLATE/next.md, ISSUE_TEMPLATE/stable.md, ISSUE_TEMPLATE/testing.md
The checklist step that points the developer to the roll out PR is missing the repository location. Add the repo location to the step to clarify where the PR will appear.
=> templates: add repo location for the roll out PR

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 37.20221106.3.0, testing 37.20221127.2.0, next 37.20221127.1.0

release-notes/next.yml, release-notes/stable.yml, release-notes/testing.yml
I had missed that this one got fixed.
See https://github.com/coreos/fedora-coreos-tracker/issues/1321
=> release-notes: add fixed issue to the record

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 37.20221127.3.0, testing 37.20221211.2.0, next 37.20221211.1.0

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
Requested by @ravanelli via [GitHub workflow](https://github.com/coreos/fedora-coreos-streams/actions/workflows/rollout.yml) ([source](https://github.com/coreos/fedora-coreos-streams/blob/main/.github/workflows/rollout.yml)).
=> Roll out stable 37.20221211.3.0, testing 37.20221225.2.1, next 37.20221225.1.1

streams/next.json, streams/testing.json, updates/next.json, updates/testing.json
=> Roll out testing 37.20221225.2.2, next 37.20221225.1.2

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 37.20221225.3.0, testing 37.20230107.2.0, next 37.20230107.1.0

updates/next.json, updates/testing.json
The new 6.0.16 kernel has a bug preventing samba mounts from working:
- https://bugzilla.redhat.com/show_bug.cgi?id=2158496
- https://bugzilla.kernel.org/show_bug.cgi?id=216895
It is fixed by 6.0.18:
https://bodhi.fedoraproject.org/updates/FEDORA-2023-9dc8ecf7fa
Stop the rollout. We'll respin `testing` and `next` with the new kernel.
=> Pause rollouts of 37.20230107.1.0 and 37.20230107.2.0

streams/next.json, streams/testing.json, updates/next.json, updates/testing.json
=> Roll out testing 37.20230110.2.0, next 37.20230110.1.0

release-notes/next.yml, release-notes/testing.yml
release-notes: updates for 20230111 releases
See: https://github.com/coreos/fedora-coreos-tracker/issues/1379
=> release-notes: updates for 20230111 releases

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 37.20230110.3.1, testing 37.20230122.2.0, next 37.20230122.1.1

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 37.20230122.3.0, testing 37.20230205.2.0, next 37.20230205.1.0

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 37.20230205.3.0, testing 37.20230218.2.0, next 37.20230218.1.0

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 37.20230218.3.0, testing 37.20230303.2.0, next 37.20230303.1.0

updates/next.json
We found a last-minute issue on updating aarch64 nodes: https://github.com/coreos/fedora-coreos-tracker/issues/1441
Let's cancel the rollout while we figure out how to address this.
=> updates/next: don't rollout f38

streams/next.json, updates/next.json
To work around https://github.com/coreos/fedora-coreos-tracker/issues/1441, we'll need to ship an F37-based barrier release that updates the bootloader before updating to F38.  Newly-deployed nodes on 38.20230310.1.0 don't need to go through that barrier release, but our Cincinnati graph builder would force it to do so anyway, causing a downgrade from F38 to F37, and that isn't necessarily safe.  38.20230310.1.0 was never rolled out and was only published for three days, so just deadend it, and roll back stream metadata.
This effectively reverts b28f0f3ce419ce318b527735f57c3e5d670ca43f.
=> next: deadend 38.20230310.1.0

updates/next.json
We need upgrading nodes to flow through 37.20230303.1.1 so they'll run the bootupctl update systemd service to update the bootloader to ensure they can boot the 6.2 kernels on aarch64.
=> updates: make 37.20230303.1.1 a barrier release

updates/testing.json
We need upgrading nodes to flow through 37.20230322.2.0 so they'll run the bootupctl update systemd service to update the bootloader to ensure they can boot the 6.2 kernels on aarch64.
=> updates: make 37.20230322.2.0 a barrier release

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 37.20230401.3.0, testing 38.20230414.2.0, next 38.20230417.1.0

updates/testing.json
We have some reports of updates not working behind a proxy in F38+ (maybe related to https://bugzilla.redhat.com/show_bug.cgi?id=2185433)
Pause the rollout while we investigate.
=> updates/testing: pause F38 rollout

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 38.20230414.3.0, testing 38.20230430.2.1, next 38.20230430.1.0

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 38.20230430.3.1, testing 38.20230514.2.0, next 38.20230514.1.0

ci/genericize-stream.py
It's a SHA-256 digest that will change with every release.
xref https://github.com/coreos/fedora-coreos-streams/pull/718
=> ci/genericize-stream: remove kubevirt digest-ref hash

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 38.20230514.3.0, testing 38.20230527.2.0, next 38.20230527.1.1

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 38.20230527.3.0, testing 38.20230609.2.1, next 38.20230609.1.0

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 38.20230609.3.0, testing 38.20230625.2.0, next 38.20230625.1.0

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 38.20230625.3.0, testing 38.20230709.2.0, next 38.20230709.1.1

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 38.20230709.3.0, testing 38.20230722.2.1, next 38.20230722.1.0

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 38.20230722.3.0, testing 38.20230806.2.0, next 38.20230806.1.0

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 38.20230806.3.0, testing 38.20230819.2.0, next 38.20230819.1.0

.github/workflows/rollout.yml
We're currently seeing an issue where the create-pull-request is running into an error:
```
2023-09-05T16:41:46.6206079Z ##[group]Create or update the pull request
2023-09-05T16:41:46.6209875Z Attempting creation of pull request
2023-09-05T16:41:49.1514174Z ##[error]invalid json response body at https://api.github.com/repos/coreos/fedora-coreos-streams/pulls reason: Unexpected end of JSON input
```
Let's try to use the latest version to see if that helps.
=> workflows/rollout: try updated create-pull-request action

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 38.20230819.3.0, testing 38.20230902.2.0, next 38.20230902.1.0

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 38.20230902.3.0, testing 38.20230918.2.0, next 39.20230916.1.1

updates/next.json
The new moby-engine can't start containers, at least on FCOS:
https://github.com/coreos/fedora-coreos-tracker/issues/1578
Pause the rollout until we find out more.
=> updates/next: pause f39 rollout

streams/stable.json, updates/stable.json
=> Roll out stable 38.20230918.3.0

streams/next.json, streams/stable.json, updates/next.json, updates/stable.json
=> Roll out stable 38.20230918.3.2, next 39.20231006.1.0

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 38.20231002.3.1, testing 38.20231014.2.0, next 39.20231016.1.0

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 38.20231014.3.0, testing 38.20231027.2.0, next 39.20231027.1.0

release-notes/next.yml, updates/testing.json
Also add release notes for `39.20231101.1.0`.
=> Add barrier for last F38 testing stream release

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 38.20231027.3.1, testing 39.20231101.2.0, next 39.20231106.1.0

.github/workflows/stream-diff.yml
The rollout workflow currently builds the generator from `git main` but the stream diff workflow expects that we use the generator from the latest tagged version.
Modify the latter so that it also uses `git describe` from `main`.
See: https://github.com/coreos/fedora-coreos-streams/pull/807#pullrequestreview-1718278962
=> workflow/stream-diff: use `git describe` tag for generator

updates/stable.json
It includes Zincati v0.0.26 which may be a culprit in
https://github.com/coreos/fedora-coreos-tracker/issues/1608
where updates appear to break in some situations.
Let's pause until we know more.
=> updates/stable: pause stable rollout

updates/testing.json
In `38.20231027.2.0` it was the last 38 release of `testing`. It also happens to be the first release with the zincati problem [1]. To avoid this problem we'll make the 38->39 update barrier (the one that satisfies https://docs.fedoraproject.org/en-US/fedora-coreos/update-barrier-signing-keys/ be `38.20231014.2.0` rather than `38.20231027.2.0`.
[1] https://github.com/coreos/fedora-coreos-tracker/issues/1608
=> Change barrier for last F38 testing stream release

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 39.20231101.3.0, testing 39.20231119.2.0, next 39.20231119.1.0

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 39.20231119.3.0, testing 39.20231204.2.1, next 39.20231204.1.0

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 39.20231204.3.3, testing 39.20240104.2.0, next 39.20240104.1.0

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 39.20240104.3.0, testing 39.20240112.2.0, next 39.20240112.1.0

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 39.20240112.3.0, testing 39.20240128.2.0, next 39.20240128.1.0

streams/next.json, streams/testing.json, updates/next.json, updates/testing.json
Requested by @ravanelli via [GitHub workflow](https://github.com/coreos/fedora-coreos-streams/actions/workflows/rollout.yml) ([source](https://github.com/coreos/fedora-coreos-streams/blob/main/.github/workflows/rollout.yml)).
=> Roll out testing 39.20240128.2.2, next 39.20240128.1.1

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 39.20240225.3.0, testing 39.20240309.2.0, next 39.20240309.1.0

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 39.20240309.3.0, testing 39.20240322.2.0, next 40.20240322.1.0

release-notes/next.yml, release-notes/stable.yml, release-notes/testing.yml, streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 39.20240322.3.1, testing 39.20240407.2.0, next 40.20240408.1.0

streams/next.json, streams/stable.json, updates/next.json, updates/stable.json
=> Roll out stable 39.20240407.3.0, next 40.20240421.1.0

rollout.py
Update location information; include time zones for all team members working on releases.
=> rollout.py: Update location information

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 40.20240416.3.1, testing 40.20240504.2.0, next 40.20240504.1.0

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 40.20240519.3.0, testing 40.20240602.2.0, next 40.20240602.1.0

updates/next.json, updates/stable.json, updates/testing.json
Let's roll out these releases today since we're already late in the week. That also allows us to set the rollout window to 48h without overlapping with the weekend.
=> Roll out 40.20240519.3.0, 40.20240602.2.0, 40.20240602.1.0 today

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 40.20240602.3.0, testing 40.20240616.2.0, next 40.20240616.1.0

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 40.20240616.3.0, testing 40.20240701.2.0, next 40.20240701.1.0

release-notes/next.yml, release-notes/testing.yml
Fixes 61a9d2b ("release-notes: updates for the 20240703 releases").
Desperately need #628.
=> release-notes: fix syntax error

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 40.20240701.3.0, testing 40.20240709.2.0, next 40.20240709.1.1

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 40.20240709.3.1, testing 40.20240728.2.1, next 40.20240728.1.1

.github/workflows/validate-release-notes.yml, ci/check-release-notes.py
This is a CI check for the release notes of [next.yml](https://github.com/coreos/fedora-coreos-streams/blob/main/release-notes/next.yml), [stable.yml](https://github.com/coreos/fedora-coreos-streams/blob/main/release-notes/stable.yml) and [testing.yml](https://github.com/coreos/fedora-coreos-streams/blob/main/release-notes/testing.yml) to catch the syntax and schema errors in these files. 
Ref: https://github.com/coreos/fedora-coreos-streams/issues/628
=> CI check for release notes YAML docs

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 40.20240728.3.0, testing 40.20240808.2.0, next 40.20240808.1.0

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 40.20240808.3.0, testing 40.20240825.2.0, next 40.20240825.1.0

release-notes/next.yml, release-notes/stable.yml, release-notes/testing.yml
Updates for the following release cycles:
- 2024-07-29
- 2024-08-12
- 2024-08-26
No noteworthy changes over those releases:
```
$ git shortlog --no-merges 6e188d56..8ee4035c
Adam Piasecki (1):
overrides: unpin selinux-policy-40.20-1.fc40
Code (1):
overrides: fast-track selinux-policy-40.27-1.fc40
CoreOS Bot (17):
lockfiles: bump to latest
lockfiles: bump to latest
lockfiles: bump to latest
lockfiles: bump to latest
lockfiles: bump to latest
lockfiles: bump to latest
lockfiles: bump to latest
lockfiles: bump to latest
lockfiles: drop graduated overrides 🎓
overrides: fast-track rust-coreos-installer-0.22.1-1.fc40
lockfiles: bump to latest
lockfiles: bump to latest
lockfiles: drop graduated overrides 🎓
lockfiles: bump to latest
lockfiles: bump to latest
lockfiles: bump to latest
lockfiles: …
```
=> release-notes: updates for last 3 release cycles

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 40.20240825.3.0, testing 40.20240906.2.0, next 40.20240906.1.0

updates/next.json
With the rollout of F41, set the n-1 build to be a release barrier.
https://docs.fedoraproject.org/en-US/fedora-coreos/update-barrier-signing-keys/
=> next: add release barrier for n-1 of first F41 release

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 40.20240906.3.0, testing 40.20240920.2.0, next 41.20240922.1.0

release-notes/next.yml
https://github.com/coreos/fedora-coreos-tracker/issues/1714#issuecomment-2426654196
Propose a release note notifying users that cgroup v1 will no longer boot by default due to systemd 256.
=> Upgrade release note to notify users of cgroup v1 no longer working

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 40.20241006.3.0, testing 40.20241019.2.0, next 41.20241020.1.0

release-notes/next.yml, release-notes/stable.yml, release-notes/testing.yml, streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 40.20241019.3.0, testing 41.20241027.2.0, next 41.20241027.1.0

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 41.20241027.3.0, testing 41.20241109.2.0, next 41.20241109.1.0

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 41.20241109.3.0, testing 41.20241122.2.0, next 41.20241122.1.0

.github/workflows/promote-config.yml
Currently, `ubuntu-latest` is still 22.04 which has git v2.34. Let's use
`fedora:latest` instead, which gives us much newer git (v2.47.1).
I suspect this should fix submodule-related issues we're seeing with
promotion:
https://github.com/coreos/fedora-coreos-config/pull/3302#issuecomment-2545817324
=> workflows/promote-config: use Fedora instead of Ubuntu

.github/workflows/promote-config.yml
To promote submodule content, we need to also make sure we clone the repo with git submodules in the first place.
=> workflows/promote-config: clone fedora-coreos-config with submodules

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 41.20241122.3.0, testing 41.20241215.2.0, next 41.20241215.1.0

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 41.20250105.3.0, testing 41.20250117.2.0, next 41.20250117.1.0

.github/workflows/print-rollouts.yml
`actions/upload-artifact` version 3 was deprecated and starting January 30, 2025, users are no longer able to use it`[1]`. Update the use of upload-artifact in the print-rollouts workflow to version 4. Uploaded artifacts are now immutable, so add `overwrite: true` as noted in the "breaking changes"`[2]`
`[1]`: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
`[2]`: https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md#overwriting-an-artifact
=> workflows/print-rollouts: bump actions/upload-artifact to v4

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 41.20250117.3.0, testing 41.20250130.2.0, next 41.20250130.1.0

ISSUE_TEMPLATE/next.md, ISSUE_TEMPLATE/stable.md, ISSUE_TEMPLATE/testing.md
Created by [GitHub workflow](https://github.com/coreos/repo-templates/actions/workflows/sync.yml) ([source](https://github.com/coreos/repo-templates/blob/main/.github/workflows/sync.yml)).
Sync with coreos/repo-templates@98f1612e98d37cdb59f8d4901148d5f350b37398.
=> Sync repo templates ⚙

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 41.20250130.3.0, testing 41.20250215.2.0, next 41.20250215.1.0

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 41.20250215.3.0, testing 41.20250302.2.0, next 41.20250302.1.0

release-notes/next.yml, release-notes/stable.yml, release-notes/testing.yml
```
marmijo@andromeda:~/coreos/fedora-coreos-config$ git shortlog --no-merges a4e1fd2..793cabb
Adam Piasecki (1):
tests/aws: Modify xen-assert to find xen entry in hypervisor string
CoreOS Bot (8):
lockfiles: bump to latest
lockfiles: bump to latest
lockfiles: bump to latest
lockfiles: bump to latest
lockfiles: bump to latest
lockfiles: bump to latest
lockfiles: bump to latest
lockfiles: bump to latest
Dusty Mabe (2):
.cci.jenkinsfile: build live and metal* together
tests/manual: trim saved state in coreos-builds-bisect.py
Jonathan Lebon (1):
tests/kola/root-reprovision/luks: don't use `root` label for LUKS device
Poorna Gottimukkula (1):
tests/kola: add test for LUKS + multipath
jbtrystram (3):
overlay/core: update target for coreos-live module
overlay/05core: coreos-ignition dracut: use …
```
=> release-notes: updates for the 2025-03-05 releases

updates/next.json
With the rollout of F42, set the n-1 build to be a release barrier.
https://docs.fedoraproject.org/en-US/fedora-coreos/update-barrier-signing-keys/
=> next: add release barrier for n-1 of first F42 release

streams/next.json
This is a partial revert of 8661997. Here we are reverting the change that rolls out our boot image bump to the website and stream metadata because we found an issue only with the bootimages.
https://github.com/coreos/fedora-coreos-tracker/issues/1913
=> Roll back next 42.20250331.1.0 stream update

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 41.20250331.3.0, testing 42.20250410.2.0, next 42.20250414.1.0

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 42.20250410.3.1, testing 42.20250427.2.0, next 42.20250427.1.0

streams/stable.json, updates/stable.json
Requested by @aaradhak via [GitHub workflow](https://github.com/coreos/fedora-coreos-streams/actions/workflows/rollout.yml) ([source](https://github.com/coreos/fedora-coreos-streams/blob/main/.github/workflows/rollout.yml)).
=> Roll out stable 42.20250410.3.2

release-notes/next.yml, release-notes/stable.yml, release-notes/testing.yml
- https://github.com/coreos/fedora-coreos-streams/issues/1053
- https://github.com/coreos/fedora-coreos-streams/issues/1055
- https://github.com/coreos/fedora-coreos-streams/issues/1056
release notes are also included for https://github.com/coreos/fedora-coreos-streams/issues/1066, so we might want to wait until it's officially released to merge this.
=> release-notes: updates for the 2025-04-29 releases

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 42.20250427.3.0, testing 42.20250512.2.0, next 42.20250512.1.0

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
Requested by @aaradhak via [GitHub workflow](https://github.com/coreos/fedora-coreos-streams/actions/workflows/rollout.yml) ([source](https://github.com/coreos/fedora-coreos-streams/blob/main/.github/workflows/rollout.yml)).
=> Roll out stable 42.20250512.3.0, testing 42.20250526.2.0, next 42.20250526.1.0

updates/next.json
The script for OCI migration first landed in 42.20250526.1.0, so let's make that a barrier even though we'll leave the code in there for now until `testing` and `stable` get migrated.
=> updates/next: make 42.20250526.1.0 a barrier for OCI migration

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 42.20250526.3.0, testing 42.20250609.2.0, next 42.20250609.1.0

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 42.20250623.3.0, testing 42.20250705.2.0, next 42.20250705.1.0

release-notes/testing.yml
We've now rolled it out to `testing`.
=> release-notes: add in OCI migration to 42.20250705.2.0

release-notes/next.yml, release-notes/stable.yml, release-notes/testing.yml
This was fixed with the new bootupd release so let's add corresponding release notes entries for it.
https://github.com/coreos/fedora-coreos-tracker/issues/1485
=> release-notes: add issue #1485 to release notes entries

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
=> Roll out stable 42.20250803.3.0, testing 42.20250818.2.0, next 42.20250818.1.0

updates/stable.json, updates/testing.json
The script for OCI migration has been in stable/testing for a while and we're ready to remove that script in favor of a new migration (that will require it's own barrier). Let's add barriers for stable/testing now for https://github.com/coreos/fedora-coreos-tracker/issues/1890
=> updates: set 42.20250901.x.0 barriers for stable/testing

streams/next.json, streams/stable.json, streams/testing.json, updates/next.json, updates/stable.json, updates/testing.json
Requested by @aaradhak via [GitHub workflow](https://github.com/coreos/fedora-coreos-streams/actions/workflows/rollout.yml) ([source](https://github.com/coreos/fedora-coreos-streams/blob/main/.github/workflows/rollout.yml)).
=> Roll out stable 42.20250901.3.0, testing 42.20250914.2.0, next 42.20250914.1.0

updates/next.json
It just so happens that there are two reasons to make 42.20250914.1.0 a barrier. It's the last `next` release of F42 AND it includes the code for migrating a system to container signature verification. Let's include the link to the signature verification migration here since that one is probably a little more significant.
=> updates/next: switch reason for 42.20250914.1.0 barrier
