- ISSUE_TEMPLATE/testing.md
Closes: https://github.com/coreos/fedora-coreos-tracker/issues/265
> checklist/testing: add steps for rolling out updates

- ISSUE_TEMPLATE/testing.md
- checklist/updates: fix `date` invocation
- checklist/updates: add some more clarity to epoch handling
- checklist/updates: update date command for last-modified field
> checklist/updates: few comment fixes for epoch handling

- ISSUE_TEMPLATE/testing.md
Some tweaks from lessons learned from a new release.
---
Don't merge yet, will likely have other tweaks as I go through the release.
> ISSUE_TEMPLATE/testing.md: more tweaks

- ISSUE_TEMPLATE/testing.md
We can simplify a lot now that the pipeline signs artifacts! :tada: 
But for now though we still need to file a releng ticket for the OSTree
import bit. Should be able to get rid of that too soon.
Requires: https://github.com/coreos/fedora-coreos-pipeline/pull/148
> ISSUE_TEMPLATE/testing.md: drop steps for manual signing

- streams/testing.json
- updates/testing.json
Note this is a barrier update due to:
https://github.com/coreos/fedora-coreos-streams/issues/26#issuecomment-558361931
> */testing: update to 30.20191014.1

- ISSUE_TEMPLATE/testing.md
Versioning is done automatically now.
> ISSUE_TEMPLATE/testing.md: stop overriding versioning

- ISSUE_TEMPLATE/stable.md
- ISSUE_TEMPLATE/testing.md
Ref: https://github.com/coreos/fedora-coreos-tracker/pull/337
> templates: fix range

- RELENG-OSTREE-IMPORT.md
Just good practice to have this documented somewhere until it's
automated for good.
> Document manual releng process for importing OSTree

- ISSUE_TEMPLATE/next.md
Prep for doing a next release.
> Add release checklist for next stream

- README.md
This should've been part of #85.
> README.md: add shortcut for creating issue from next template

- streams/next.json
- streams/stable.json
- streams/testing.json
- updates/next.json
- updates/stable.json
- updates/testing.json
This schedules rollouts for latest stable/testing/next releases,
starting on 2020-05-19.
> updates: triple rollout on 2020-05-19

- ISSUE_TEMPLATE/next.md
- ISSUE_TEMPLATE/stable.md
- ISSUE_TEMPLATE/testing.md
> issue_template: rectify the argument for cosa run command

- streams/next.json
- updates/next.json
See the following issue for context:
https://github.com/coreos/fedora-coreos-tracker/issues/484#issuecomment-649009580
> next: rollout 32.20200615.1.3 barrier release

- ISSUE_TEMPLATE/next.md
- ISSUE_TEMPLATE/stable.md
- ISSUE_TEMPLATE/testing.md
Avoid releasers a bunch of searching and typing.
> templates: link to sync-stream-metadata job

- streams/next.json
- streams/stable.json
- streams/testing.json
- updates/next.json
- updates/stable.json
- updates/testing.json
* next: 32.20200726.1.0
* testing: 32.20200726.2.0
* stable: 32.20200715.3.0
> updates: triple rollout on 2020-07-28

- streams/next.json
- streams/stable.json
- streams/testing.json
- updates/next.json
- updates/stable.json
- updates/testing.json
* next: 32.20200809.1.1
* testing: 32.20200809.2.1
* stable: 32.20200726.3.1
> updates: triple rollout on 2020-08-12

- streams/stable.json
- updates/stable.json
Set to start at 2020/09/08 15:30UTC
> stable: rollout 32.20200824.3.0

- streams/testing.json
- updates/testing.json
> testing: rollout 32.20200907.2.2

- streams/stable.json
- updates/stable.json
> stable: rollout 32.20200907.3.0

- streams/next.json
- updates/next.json
> next: rollout 32.20200923.1.0

- streams/testing.json
- updates/testing.json
> testing: rollout 32.20200923.2.0

- streams/stable.json
- streams/testing.json
- updates/stable.json
- updates/testing.json
stable: 32.20201004.3.0
testing: 32.20201018.2.0
> updates: stable and testing streams rollout on 2020-10-20

- ISSUE_TEMPLATE/next.md
- ISSUE_TEMPLATE/testing.md
> templates: be more explicit re. graduated overrides

- streams/next.json
- updates/next.json
See https://github.com/coreos/fedora-coreos-tracker/issues/646
> next: rollout 33.20201020.1.0 (barrier release)

- streams/stable.json
- updates/stable.json
Starting at 2020/11/17 18:00UTC
> stable: rollout 32.20201104.3.0

- streams/next.json
- updates/next.json
> next: rollout 33.20201130.1.0

- streams/testing.json
- updates/testing.json
> testing: rollout 33.20201201.2.0

- updates/testing.json
Investigating a potential issue over in
https://github.com/coreos/fedora-coreos-tracker/issues/700
> testing: pause rollout of 33.20201201.2.1

- streams/next.json
- streams/stable.json
- streams/testing.json
- updates/next.json
- updates/stable.json
- updates/testing.json
stable: 33.20210104.3.0"
testing: 33.20210117.2.0
next: 33.20210117.1.0
> updates: tripple rolling update

- streams/next.json
- streams/stable.json
- streams/testing.json
- updates/next.json
- updates/stable.json
- updates/testing.json
- stable 33.20210201.3.0: https://github.com/coreos/fedora-coreos-streams/issues/261
- testing 33.20210217.2.0: https://github.com/coreos/fedora-coreos-streams/issues/262
- next 33.20210217.1.0: https://github.com/coreos/fedora-coreos-streams/issues/263
> Triple rollout

- ISSUE_TEMPLATE/next.md
- ISSUE_TEMPLATE/stable.md
- ISSUE_TEMPLATE/testing.md
Last release issues where not Jira'd thus I forgot about them during planning.
> templates: Add assigning the GH issue and Jira card to the next person

- streams/stable.json
- updates/stable.json
> stable: rollout 33.20210217.3.0

- streams/testing.json
- updates/testing.json
> testing: rollout 33.20210301.2.0

- streams/next.json
- updates/next.json
> next: rollout 33.20210302.1.0

- streams/stable.json
- updates/stable.json
> stable: rollout 34.20210427.3.0

- streams/testing.json
- updates/testing.json
> testing: rollout 34.20210518.2.0

- streams/next.json
- updates/next.json
> next: rollout 34.20210518.1.0

- ISSUE_TEMPLATE/next.md
- ISSUE_TEMPLATE/testing.md
This is automatically done now.
> ISSUE_TEMPLATE: stop manually checking for graduated overrides

- rollout.py
This is an easy way to sanity-check that the build IDs match up. The
version we rollout should almost always match what the latest release on
that stream is. Add a check for this.
So... this script now does networking. Which should be fine in most
cases, but add a switch in case a user doesn't want to depend on the
network.
> rollout.py: check whether rollout matches latest release

- streams/stable.json
- updates/stable.json
> stable: rollout 34.20210725.3.0

- streams/testing.json
- updates/testing.json
> testing: rollout 34.20210808.2.0

- streams/next.json
- updates/next.json
> next: rollout 34.20210808.1.0

- ISSUE_TEMPLATE/next.md
- ISSUE_TEMPLATE/stable.md
- ISSUE_TEMPLATE/testing.md
Now that we have a second architecture, let's add some checks for it
too.
> templates: add considerations for aarch64

- streams/next.json
- updates/next.json
First Fedora 35 based release! Add barrier as instructed by
https://github.com/coreos/fedora-coreos-tracker/issues/884
> next: rollout 35.20210924.1.0

- ISSUE_TEMPLATE/next.md
- ISSUE_TEMPLATE/stable.md
- ISSUE_TEMPLATE/testing.md
We're doing testing there so let's add it to the checklist.
> templates: add aarch64 for checkbox for OpenStack

- RELEASE.md
But really this is test that webhooks are working.
> RELEASE.md: add missing period

- ISSUE_TEMPLATE/next.md
- ISSUE_TEMPLATE/stable.md
- ISSUE_TEMPLATE/testing.md
Now that we are testing on Azure let's verify the tests passed.
> templates: add check for Azure tests

- streams/next.json
- updates/next.json
> Roll out next 36.20220418.1.0

- streams/next.json
- streams/stable.json
- streams/testing.json
- updates/next.json
> Roll out next 36.20220430.1.0

- streams/next.json
- updates/next.json
> Roll out next 36.20220505.1.0

- release-notes/next.yml
- release-notes/stable.yml
- release-notes/testing.yml
release-notes: Add releases without notes
Include them to be able to differentiate:
- release with no specific release notes
- from release where we have not yet reviewed the notes
---
release-notes: Fix wrong stream/version in testing notes
---
release-notes: Update for new releases
> release-notes: Update for new releases

- release-notes/next.yml
- release-notes/stable.yml
- release-notes/testing.yml
Also retroactively add #1218 to last week's next/testing.
> release-notes: updates for this week's releases

- ISSUE_TEMPLATE/next.md
- ISSUE_TEMPLATE/stable.md
- ISSUE_TEMPLATE/testing.md
Created by [GitHub workflow](https://github.com/coreos/repo-templates/actions/workflows/sync.yml) ([source](https://github.com/coreos/repo-templates/blob/main/.github/workflows/sync.yml)).
Sync with coreos/repo-templates@0638e58aed73dcf92b924a5d9020a8231d8e6f4d.
> Sync repo templates ⚙

- streams/next.json
- updates/next.json
> Roll out next 37.20220910.1.0

- streams/next.json
- updates/next.json
> Roll out next 37.20221008.1.0

- streams/next.json
- updates/next.json
> Roll out next 37.20221021.1.0

- release-notes/stable.yml
- release-notes/testing.yml
> release-notes: fix typos from previous commit

- release-notes/next.yml
> release-notes: fix typos for next from earlier commit

- updates/next.json
https://github.com/coreos/fedora-coreos-tracker/issues/1333#issuecomment-1319168915
> next: add barrier for GRUB Password CVE-2022-3675

- .github/workflows/post-rollouts.yml
- .github/workflows/print-rollouts.yml
- .github/workflows/promote-config.yml
- .github/workflows/rollout.yml
- .github/workflows/stream-diff.yml
- .github/workflows/validate.yml
Fixes [deprecation warnings](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) for Node.js 12.
> workflows: update actions to current major versions

- streams/next.json
- updates/next.json
> Roll out next 38.20230310.1.0

- streams/next.json
- updates/next.json
> Roll out next 38.20230408.1.1

- streams/next.json
- updates/next.json
> Roll out next 38.20230414.1.0

- release-notes/testing.yml
- streams/testing.json
- updates/testing.json
> Roll out testing 38.20230414.2.1

- streams/next.json
- streams/testing.json
- updates/next.json
- updates/testing.json
> Roll out testing 38.20230902.2.1, next 38.20230902.1.1

- streams/next.json
- updates/next.json
> Roll out next 39.20230916.1.2

- streams/next.json
- streams/testing.json
- updates/next.json
- updates/testing.json
> Roll out testing 38.20231002.2.2, next 39.20231002.1.1

- streams/next.json
- updates/next.json
> Roll out next 39.20231022.1.0

- streams/stable.json
- updates/stable.json
> Roll out stable 38.20231027.3.2

- streams/next.json
- streams/testing.json
- updates/next.json
- updates/testing.json
> Roll out testing 39.20231101.2.1, next 39.20231106.1.1

- updates/next.json
- updates/testing.json
See https://github.com/coreos/fedora-coreos-tracker/issues/1637#issuecomment-1878186381
> Add barriers for testing/next 39.20240104.x.0

- streams/next.json
- updates/next.json
> Roll out next 40.20240331.1.0

- streams/stable.json
- updates/stable.json
> Roll out stable 39.20240322.3.0

- release-notes/next.yml
- release-notes/stable.yml
- release-notes/testing.yml
- stable release went out Monday
- next release went out last week
- identified a new issue that was fixed in all 3 streams at various times
> release-notes: a few misc release notes updates

- .github/workflows/promote-config.yml
- .github/workflows/rollout.yml
Ref: https://github.com/coreos/fedora-coreos-tracker/issues/1699
> Update peter-evans/create-pull-request to v6

- streams/next.json
- updates/next.json
> Roll out next 40.20240416.1.0

- streams/testing.json
- updates/testing.json
> Roll out testing 40.20240416.2.0

- release-notes/next.yml
- release-notes/stable.yml
- release-notes/testing.yml
Also retroactively add some links to rebase trackers for F40/F39.
> release-notes: updates for the 20240423 releases

- release-notes/next.yml
- release-notes/stable.yml
- release-notes/testing.yml
includes updates for the following:
- 2024-05-21:
- https://github.com/coreos/fedora-coreos-tracker/issues/1653
- 2024-06-03
- 2024-06-17:
- https://github.com/coreos/fedora-coreos-tracker/issues/1722
> release-notes: updates for the past three FCOS releases

- streams/next.json
- updates/next.json
> Roll out next 41.20240916.1.0

- release-notes/next.yml
- release-notes/stable.yml
- release-notes/testing.yml
Release notes updates for the 2024-09-24 and 2024-10-08 releases
> release-notes: updates for the past two release cycles

- streams/next.json
- updates/next.json
> Roll out next 41.20241024.1.0

- release-notes/next.yml
- release-notes/stable.yml
- release-notes/testing.yml
- https://github.com/coreos/fedora-coreos-streams/issues/995
- https://github.com/coreos/fedora-coreos-streams/issues/994
- https://github.com/coreos/fedora-coreos-streams/issues/993
- https://github.com/coreos/fedora-coreos-streams/pull/1000
> release-notes: updates for 2024-12-17 releases

- release-notes/next.yml
- release-notes/stable.yml
- release-notes/testing.yml
- https://github.com/coreos/fedora-coreos-streams/issues/1001
- https://github.com/coreos/fedora-coreos-streams/issues/1002
- https://github.com/coreos/fedora-coreos-streams/issues/1003
- https://github.com/coreos/fedora-coreos-streams/pull/1005
> release-notes: updates for 2025-01-07 releases

- streams/stable.json
- updates/stable.json
Requested by @aaradhak via [GitHub workflow](https://github.com/coreos/fedora-coreos-streams/actions/workflows/rollout.yml) ([source](https://github.com/coreos/fedora-coreos-streams/blob/main/.github/workflows/rollout.yml)).
> Roll out stable 41.20250315.3.0

- streams/next.json
- updates/next.json
> Roll out next 42.20250410.1.1

- streams/testing.json
- updates/testing.json
> Roll out testing 42.20250410.2.1

- release-notes/next.yml
- release-notes/stable.yml
- release-notes/testing.yml
notes are also included for the 2025-04-10 `next` release, and the 2025-04-23 `testing` release.
> release-notes: updates for the 2025-04-15 releases

- release-notes/next.yml
- release-notes/stable.yml
- release-notes/testing.yml
- https://github.com/coreos/fedora-coreos-streams/issues/1086
- https://github.com/coreos/fedora-coreos-streams/issues/1084
- https://github.com/coreos/fedora-coreos-streams/issues/1085
> release-notes: updates for the 2025-06-24 releases

- streams/next.json
- updates/next.json
> Roll out next 43.20250917.1.0

- release-notes/next.yml
- https://github.com/coreos/fedora-coreos-streams/issues/1129
> release-notes/next: update for the 2025-09-18 release

- streams/next.json
- updates/next.json
Requested by @tlbueno via [GitHub workflow](https://github.com/coreos/fedora-coreos-streams/actions/workflows/rollout.yml) ([source](https://github.com/coreos/fedora-coreos-streams/blob/main/.github/workflows/rollout.yml)).
> Roll out next 43.20250929.1.0
